package me.xiaozhangup.carb.database

import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.ResultSet
import java.sql.Statement
import javax.sql.DataSource

/**
 * 标识符引用方言
 */
enum class IdentifierQuoter(val open: String, val close: String) {
    /** MySQL / SQLite / H2 */
    BACKTICK("`", "`"),
    /** PostgreSQL */
    DOUBLE_QUOTE("\"", "\"")
}

/**
 * 当前线程的标识符引用方言，默认为反引号（MySQL/SQLite/H2）
 */
val currentQuoter = ThreadLocal.withInitial { IdentifierQuoter.BACKTICK }

/**
 * 根据 Host 类型设置当前线程的标识符引用方言
 */
fun setupQuoterForHost(host: Host<*>) {
    currentQuoter.set(
        if (host is HostPostgreSQL) IdentifierQuoter.DOUBLE_QUOTE
        else IdentifierQuoter.BACKTICK
    )
}

@Suppress("SqlSourceToSinkFlow")
fun <T> DataSource.open(query: String, autoGeneratedKeys: Int = Statement.RETURN_GENERATED_KEYS, work: (connection: Connection, statement: PreparedStatement) -> T): T {
    return connection.use { connection ->
        connection.prepareStatement(query, autoGeneratedKeys).use { prepareStatement ->
            work(connection, prepareStatement)
        }
    }
}

fun <T> ResultSet.use(func: (resultSet: ResultSet) -> T): T {
    return try {
        func(this)
    } catch (ex: Exception) {
        throw ex
    } finally {
        close()
    }
}

fun <T> Connection.use(func: (connection: Connection) -> T): T {
    return try {
        func(this)
    } catch (ex: Exception) {
        throw ex
    } finally {
        close()
    }
}

fun <T> PreparedStatement.use(func: (statement: PreparedStatement) -> T): T {
    return try {
        func(this)
    } catch (ex: Exception) {
        throw ex
    } finally {
        close()
    }
}

/**
 * 尝试格式化一个列名
 */
fun Any.asFormattedColumnName(): String {
    val str = this.toString()
    val q = currentQuoter.get()
    // 如果字符串是 "*" 或 "null" || 如果字符串是一个函数或表达式
    if (str == "*" || str == "null" || str.contains(Regex("\\(.*\\)"))) return str
    // 如果字符串已经用当前 quoter 格式化
    if (str.startsWith(q.open) && str.endsWith(q.close)) return str
    // 如果字符串用了错误的 quoter（如 PostgreSQL 下使用了反引号），替换为正确的
    val other = if (q == IdentifierQuoter.BACKTICK) IdentifierQuoter.DOUBLE_QUOTE else IdentifierQuoter.BACKTICK
    if (str.contains(other.open)) {
        return str.replace(other.open, q.open).replace(other.close, q.close)
    }
    // 通过 "." 分割字符串并分别格式化每个部分
    val parts = str.split(".")
    return parts.joinToString(".") { "${q.open}$it${q.close}" }
}