name: CarbKotlin
main: xyz.gmitch215.kotlinmc.Spigot
version: ${project.ext.kotlin_version}
description: ${project.description}
api-version: 1.21.4
author: gmitch215
load: ROOT
website: ${project.ext.url}
